Fix helm 3 crds installation
Orange-OpenSource/casskop pull request #282
Opened 2020-11-26 14:11 UTC by PERES-Richard

| Q               | A
| --------------- | ---
| Bug fix?        | [x]

### What's in this PR?

### Why?
The actual installation with helm 3 use a crd-install hook wich is depreciated in helm 3. With this fix you can now install Casskop (CRD + operator) with just 1 line of helm.

### Additional context
It simply consist of copying CRDs from /deploy/crds to helm folders of Casskop & Multi Casskop.

### Checklist

- [ ] Implementation tested
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)
- [ ] Append changelog

### To Do
- [ ] Test & changelog

2020-12-03 00:54 UTC, cscetbon commented
@PERES-Richard are you sure helm2 still works with those changes ? #133 seems to say it doesn't. And if doesn't I think we can drop support for helm 2.

2020-12-03 00:59 UTC, cscetbon requested changes

2020-12-03 00:59 UTC, cscetbon commented on website/docs/5_operations/3_5_backup_restore.md
>      name: nightly-cassandra-backup
no subkey

2020-12-03 10:56 UTC, PERES-Richard commented on website/docs/5_operations/3_5_backup_restore.md
>      name: nightly-cassandra-backup
done !

2020-12-08 18:56 UTC, cscetbon approved these changes

2020-12-08 18:56 UTC, cscetbon commented on website/docs/2_setup/1_getting_started.md
> +Then install the chartusing Helm 3:
chart` `using

2020-12-08 18:57 UTC, cscetbon commented on website/docs/2_setup/1_getting_started.md
> +Then install the chartusing Helm 3:
```suggestion
Then install the chart using Helm 3:
```

2020-12-10 10:06 UTC, fdehay approved these changes
We should have left Kuttl out of the PR but it's ok

2020-12-10 14:19 UTC, merged