Enforce HARDLINKS restore strategy as it is faster
Orange-OpenSource/casskop pull request #290
Opened 2021-01-15 02:34 UTC by cscetbon

IMPORT restore strategy implies reading sstables and rewriting them which is longer that using hardlinks. That PR enforces that choice.

2021-01-18 08:42 UTC, PERES-Richard requested changes
I think this should be also removed : 
https://github.com/Orange-OpenSource/casskop/blob/7fc9abf7ea8fc0c950b773901e6a6e972c8b4884/pkg/apis/db/v1alpha1/common/test.go#L28

And also the doc should be updated as well
https://github.com/Orange-OpenSource/casskop/blob/restore-strategy/website/docs/6_references/6_cassandra_restore.md

(in YAML example & table row)

2021-01-18 16:15 UTC, cscetbon commented
@PERES-Richard I agree on the doc but not on the test. It's the response returned by the client and it always include the restore strategy

2021-01-19 15:15 UTC, PERES-Richard commented
> @PERES-Richard I agree on the doc but not on the test. It's the response returned by the client and it always includes the restore strategy

Okey. I will test this new implem on our cluster to strongly assert that this will not break backup & restore flows :)

2021-01-26 15:28 UTC, PERES-Richard approved these changes

2021-01-26 15:35 UTC, merged