Custom user auth changes
Orange-OpenSource/casskop pull request #306
Opened 2021-03-02 08:30 UTC by SuhailRahman

| Q               | A
| --------------- | ---
| New feature?    | [X]
| License         | Apache 2.0

### What's in this PR?
 This PR has the extended functionality of running a custom script when the Cassandra pod is started up, using the postStart lifecycle hook. One use case is when the user wishes to create custom roles on the startup of Cassandra
### Why?
In case a user wishes to perform an operation immediately after Cassandra is started up, such as create a role with cqlsh, the script specified by /etc/cassandra_post_start.sh can be injected via configmap to run on post-start.

2021-03-12 06:53 UTC, ajaybhat commented
@cscetbon can you please review this

2021-03-14 03:43 UTC, cscetbon requested changes

2021-03-14 03:43 UTC, cscetbon commented on pkg/controller/cassandracluster/generator.go
> +						"/etc/cassandra/cassandra_post_start.sh",
Your changes would make any deployment that doesn't provide that script fail. Your PostStart action should check if the file exists and if it does should run.

Also it doesn't mean that cassandra was started but just that the container was started as it's mentioned in the documentation _"There is no guarantee, however, that the postStart handler is called before the Container's entrypoint is called"_
So I think there is still some work missing here

2021-03-23 23:41 UTC, cscetbon commented on pkg/controller/cassandracluster/generator.go
> +						"/etc/cassandra/cassandra_post_start.sh",
@ajaybhat @SuhailRahman 👆

2021-05-05 03:54 UTC, cscetbon commented
Closing the PR for now as it's been opened for more than a month. Reopen it when you have more time to work on it. Thanks

2021-05-05 03:54 UTC, closed without merging