Patch kuttl test to work with releases
Orange-OpenSource/casskop pull request #307
Opened 2021-03-02 10:42 UTC by fdehay

Patch init script to work for releases

| Q               | A
| --------------- | ---
| Bug fix?        | [X]

### What's in this PR?
Fix the image choosing algo to work with release tags in the kuttl ScaleUpandDown tests

### Why?
Kuttl tests were failing when release were made

2021-03-14 03:37 UTC, cscetbon requested changes

2021-03-14 03:37 UTC, cscetbon commented on test/e2e/kuttl/ScaleUpAndDown/00-createCluster.yaml
> +      fi
@fdehay I would rather do 
```
VERSION=${CIRCLE_TAG:-CIRCLE_BRANCH}
```
I don't think we need to check the file at any point as we already use the right version in the tag

2021-03-15 08:55 UTC, fdehay commented
CIRCLE_TAG is empty if you are not releasing / tagging.
And if we don't check the file we do not know the current version


Le dim. 14 mars 2021 à 04:38, Cyril Scetbon ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In test/e2e/kuttl/ScaleUpAndDown/00-createCluster.yaml
> <https://github.com/Orange-OpenSource/casskop/pull/307#discussion_r593835918>
> :
>
> > @@ -3,7 +3,12 @@ kind: TestStep
>  commands:
>    - script: |
>        BASEDIR=../../../..
> -      VERSION=$(awk -F\" '/Version =/ {print $2}' $BASEDIR/version/version.go)-$CIRCLE_BRANCH
> +      if [ $CIRCLE_TAG ]
> +        then
> +          VERSION="$(awk -F\" '/Version =/ {print $2}' $BASEDIR/version/version.go)-release"
> +        else
> +          VERSION="$(awk -F\" '/Version =/ {print $2}' $BASEDIR/version/version.go)-$CIRCLE_BRANCH"
> +      fi
>
> @fdehay <https://github.com/fdehay> I would rather do
>
> VERSION=${CIRCLE_TAG:-CIRCLE_BRANCH}
>
> I don't think we need to check the file at any point as we already use the
> right version in the tag
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Orange-OpenSource/casskop/pull/307#pullrequestreview-611656353>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB4BEQM6FBF6MJCFC2FTOBTTDQOQPANCNFSM4YOWCAVA>
> .
>

2021-03-17 13:17 UTC, cscetbon commented on test/e2e/kuttl/ScaleUpAndDown/00-createCluster.yaml
> +      fi
```suggestion
     VERSION=${CIRCLE_TAG:-CIRCLE_BRANCH}
```

2021-05-02 04:13 UTC, cscetbon commented
@fdehay any news on that PR ? Is it still needed ?

2021-05-05 03:52 UTC, cscetbon approved these changes

2021-05-05 03:53 UTC, merged