Added a possibility to configure readinessProbe timeouts for operator deployment
Orange-OpenSource/casskop pull request #362
Opened 2021-09-14 09:52 UTC by ajoskowski

| Q               | A
| --------------- | ---
| Bug fix?        | []
| New feature?    | [YES]
| API breaks?     | []
| Deprecations?   | []
| Related tickets | fixes #360 
| License         | Apache 2.0

### What's in this PR?
Added a possibility to configure readinessProbe timeouts for operator deployment via `values.yaml` file.

### Why?
We encountered on a problem that after upgrade of operator its deployment object cannot be marked as "ready".
There is a workaround: we have to increase "failureThreshold" timeout to value higher than 1s and everything works correctly

### Checklist
- [X] Implementation tested

2021-09-14 14:48 UTC, PERES-Richard commented
Hi, can you also update the documentation as well please.

=> https://github.com/Orange-OpenSource/casskop/blob/master/website/docs/3_configuration_deployment/1_customizable_install_with_helm.md 

@cscetbon What do you think ?

2021-09-14 14:51 UTC, PERES-Richard requested changes
https://github.com/Orange-OpenSource/casskop/blob/master/website/docs/3_configuration_deployment/1_customizable_install_with_helm.md

2021-09-15 05:11 UTC, ajoskowski commented
> Hi, can you also update the documentation as well please.
> 
> => https://github.com/Orange-OpenSource/casskop/blob/master/website/docs/3_configuration_deployment/1_customizable_install_with_helm.md
> 
> @cscetbon What do you think ?

Updated docs

2021-09-15 09:07 UTC, PERES-Richard approved these changes

2021-09-15 09:07 UTC, merged